# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://mengwangk.github.io/{{ cookiecutter.package_name }}/"

git_url = "https://github.com/mengwangk/{{ cookiecutter.package_name }}/tree/master/"

def custom_doc_links(name): return None
